### ISSUE TITLE
Determine if black should also be pointed to tests

### ISSUE THREAD

**Issue by cwkingjr** [charwking/gift-exchange-app#11]
I noticed that the indentation in tests is 3 spaces, which is normally 4 by black/pep8. If we pointed black to tests, it would fix these on new commits. But, it might freak out about other stuff.

**Comment by charwking** [comment]
I like the idea of auto-formatting the tests too. I tried it locally and the tests still pass. I can't think of any reason why it would be harmful. Can you?

**Comment by charwking** [comment]
> I noticed that the indentation in tests is 3 spaces

That was just my default in vim. If 4 is idiomatic, I'm all for that... and can easily make spaces-per-tab language-specific in vim.
