### ISSUE TITLE
Add jinja template

### ISSUE THREAD

**Issue by charwking** [charwking/gift-exchange-app#8]
The index endpoint should return an HTML page, rendered with a Jinja template, that says "Hello world" and the current server date/time (just so there's something dynamic on the page).

**Comment by cwkingjr** [comment]
I was looking around to determine how to integrate jinja2 into cherrypy. I found this gist, but I don't know if it's the best way. https://gist.github.com/jhargis/b1bf47bd03e83930e346

**Comment by cwkingjr** [comment]
At least at some point, cherrypy included its own templating system called kid. https://www.tutorialspoint.com/cherrypy/cherrypy_presentation_layer.htm
